name: Compile with SourceMod

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        sm_version: ['1.8', '1.9', '1.10', '1.11']

    steps:
      - uses: actions/checkout@v1

      - name: Setup Environment
        run: |
          SOURCEMOD_PATH=$GITHUB_WORKSPACE/addons/sourcemod
          echo ::set-env name=SOURCEMOD_PATH::$SOURCEMOD_PATH
          echo ::set-env name=SCRIPTS_PATH::$SOURCEMOD_PATH/scripting

      - name: Setup SourcePawn Compiler
        uses: rumblefrog/setup-sp@master
        with:
          version: ${{ matrix.sm_version }}

      - name: Compile Plugin
        run: spcomp $SCRIPTS_PATH/testsuite_example.sp -i$SCRIPTS_PATH/include -O2 -t4 -v2
